### ISSUE TITLE
DatWeatherDoe-1.21.dmg file blank. 

### ISSUE THREAD

**Issue by nathancooperjones** [inderdhir/DatWeatherDoe#10]
After downloading the latest executable build, I get nothing. 

<img width="930" alt="screen shot 2018-10-12 at 12 27 42 pm" src="https://user-images.githubusercontent.com/31417712/46884298-38aaf680-ce1a-11e8-8d94-51255f1b7da3.png">

**Comment by inderdhir** [comment]
My bad, missed this. I believe it was an issue with the dmg generation. Please check out the latest release!
