### ISSUE TITLE
Feature Request: mph for wind speed

### ISSUE THREAD

**Issue by mathomp4** [inderdhir/DatWeatherDoe#104]
Just discovered this app and am loving it!

That said, could you add the option to display the wind speed in mph as well as m/s? I suppose it could either be a different dropdown (like Fahrenheit) or make that an Imperial/Metric dropdown? Not sure.

**Comment by CarlSustrich** [comment]
I second this comment! Love the simplicity of this app

**Comment by inderdhir** [comment]
This is included in the recent versions where "unit" can be set to metric/imperial.
