### ISSUE TITLE
Show complete weather option does not work when weather source is set to postal code

### ISSUE THREAD

**Issue by ogig33** [inderdhir/DatWeatherDoe#105]
# Issue

When `Weather source` is set to "Postal code", the menu option `Show complete weather` opens https://openweathermap.org/city/0 in the browser (= London, GB) regardless of the actual postal code set in DatWeatherDoe.

# Expected behaviour 

OpenWeatherMap site is opened with the location configured in DatWeatherDoe.

# Steps to reproduce

1. Choose `Configure` menu item 
2. Set `Weather source` to "Postal code"
3. Set `Postal code` to "50769,de"
4. Choose `Show complete weather` menu item
5. Check browser for the location show in the OpenWeatherMap website

# Environment
macOS 13.1
DatWeatherDoe 3.2

**Comment by inderdhir** [comment]
Can you try with 5.0.0? The app now uses WeatherAPI
