### ISSUE TITLE
Zipcode fail + Location fail

### ISSUE THREAD

**Issue by SenpaiHunters** [inderdhir/DatWeatherDoe#108]
As of V 3.2.1 you can no longer use any other Zipcode, I.E., only accepts American Zipcodes now, as before i was able to use an Aus/Jpn Zipcode. Hopefully this gets fixed! As, the 'location' feature is also faulty, it's not correctly showing my location (I won't say where for privacy reasons, but it's nowhere close to me) about 1,200km away from my actual location.

**Comment by 71m383nd3r** [comment]
@SenpaiHunters 
try to use zipcode + country code
[List of country code](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) use [alpha-2] – two-letter country codes


**_try & test_**

10000,hr
10115,de
2000,au
10002,us
