### ISSUE TITLE
Crash on incorrect postal code - impossible to correct

### ISSUE THREAD

**Issue by Arnoud-B** [inderdhir/DatWeatherDoe#11]
Entering an incorrect postal code makes the app invisible in the menu bar, after which it seems there is no way to access the settings to change the postal code. I tried finding it in the plist or other files but couldn't locate where the postal code is stored. Uninstalling the app with an uninstaller like TrashMe and then reinstalling it also didn't solve the issue.

In the end I found out there is a tiny invisible bar in the menu bar that you can click on to reconfigure the app. Perhaps it would be good to have "N/A" or some default icon displayed in the menu bar when data cannot be retrieved, so at least the settings are easily accessible and it's clear the app has launched and not crashed?

**Comment by inderdhir** [comment]
That's interesting coz the location is saved using NSUserDefaults. Ill check it out

**Comment by inderdhir** [comment]
@Arnoud-B 1.2.4 was just released, let me know if that fixes it for ya :)

**Comment by Arnoud-B** [comment]
Yep, it now shows a sun when the postal code is not recognized. Not the clearest message, but at least it remains accessible :) Thanks!
