### ISSUE TITLE
Brew install how to set API Key?

### ISSUE THREAD

**Issue by webber-naut** [inderdhir/DatWeatherDoe#117]
Forgive the noob question. But if I used brew to install where would I find the Config.xcconfig file exactly?

> 
> Developer Setup
> 
>     Get your personal API key for openweathermap [here](http://openweathermap.org/appid)
>     Add the following in "Config.xcconfig":
> 
> OPENWEATHERMAP_APP_ID = YOUR_KEY

**Comment by inderdhir** [comment]
It's in the root directory: https://github.com/inderdhir/DatWeatherDoe/blob/main/Config.xcconfig

**Comment by webber-naut** [comment]
I was getting a network error so I thought I needed my own API key, but turns out it was related to this bug.
[Zipcode fail + Location fail #108](https://github.com/inderdhir/DatWeatherDoe/issues/108)

Setting the lat and long in the app configure fixed my issue.
