### ISSUE TITLE
Single key shortcuts

### ISSUE THREAD

**Issue by eugenesvk** [inderdhir/DatWeatherDoe#122]
Since shortcuts are only active once you click on the menubar and there is no text input that would require non-modifier keys, requiring <kbd>⇧</kbd><kbd>⌘</kbd> prefix seems excessive

Is it possible to just use single-key shortcuts? So <kbd>R</kbd> would refresh without any modifiers

**Comment by inderdhir** [comment]
This will be part of next release. It seems like "command" press will be required but I have removed the "Shift" requirement: https://github.com/inderdhir/DatWeatherDoe/commit/37f23889572dd8f4c42033b1894cf51373486a7c

**Comment by eugenesvk** [comment]
Thanks!
Is it possible to add something like [var keyEquivalentModifierMask: NSEvent.ModifierFlags](https://developer.apple.com/documentation/appkit/nsmenuitem/1514815-keyequivalentmodifiermask)
and specify a no-modifier mask for the menus?
similar to this example
```swift
item.keyEquivalent = "f"
item.keyEquivalentModifierMask = []
```
