### ISSUE TITLE
Version 4 is a downgrade

### ISSUE THREAD

**Issue by shahin365** [inderdhir/DatWeatherDoe#128]
used this app because it showed the temperature in F° and C° simultaneity on the menu bar. disappointed to see the option disappeared on the version 4 and forced me to switch back to version 3. please add it back.

**Comment by inderdhir** [comment]
Please check out 4.0.0 Beta 2 which adds back support for this. https://github.com/inderdhir/DatWeatherDoe/releases/tag/4.0.0-beta.2
