### ISSUE TITLE
bug report and suggestion

### ISSUE THREAD

**Issue by shahin365** [inderdhir/DatWeatherDoe#129]
Thank you for the new update. being able to hide the unit of the temperature is definitely helpful to save space on the already cramped menu bar.

However, there is one issue that hasn’t been fixed in this new update. unlike all other macOS new apps if you make changes in the configuration window changes don’t apply unless you press done and close the configure window. moreover, the configuration window won’t go away when you click on the free space on the desktop and you must click on the done button to close the window. it’s very annoying and gives me the feeling that it’s an outdated app that hasn’t been updated since OSX Yosemite.

plus, the short weather description should be after the temperature not the other way around, and there is no need for a comma.

![in](https://github.com/inderdhir/DatWeatherDoe/assets/16749755/2e6545fa-53c6-41a9-8023-0d011cfc3587)

also, can you add the version number configuration window?

thank you again,
P.S. I'm not sure what the _separate the value with_ does?
P.S.2 Why the version 4.00 is not available on brew?

**Comment by inderdhir** [comment]
Changes are part of 4.1.0.
- Closing configure upon clicking outside has been fixed
- Switched the order of weather description
- Added version in Settings
- Separating values is used when both temperature and humidity are shown

The release should be up on brew shortly.
