### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by ytain** [inderdhir/DatWeatherDoe#130]
I'm getting ```Network Error``` with the version 4.1.1 in the menu bar. I installed it via brew for the previous version and it worked then today it upgraded and it stopped working, showing this error.

------------

Had to go to previous version and it works just fine.

Also the 4.1.1 is missing the ```OPENWEATHERMAP_APP_ID``` value in the file ```Info.plist```

**Comment by inderdhir** [comment]
Fixed in 4.1.2
