### ISSUE TITLE
Cancelled message

### ISSUE THREAD

**Issue by shahin365** [inderdhir/DatWeatherDoe#131]
Every time I refresh by pressing R or clicking on the Refresh button, it displays the message "Canceled" in place of the temperature for 1-2 seconds, then it shows the new temperature. Can you please fix it?

P.S. Please add the version number to the configure page.
P.S.2 The configure page won't close until you press "Done." It's not a big deal, but it's annoying.

**Comment by inderdhir** [comment]
Fixed in 4.1.2
