### ISSUE TITLE
App Never In Menu Bar Since Update To 4.1.2

### ISSUE THREAD

**Issue by highschooldropout** [inderdhir/DatWeatherDoe#132]
Latest version of MacOS (14.1.2), latest version of the app (4.1.2).

After restart and even after sleep, app is never in the menu bar. And yes, it's set to "Open at Login."

**Comment by miszterx** [comment]
Same here. Same OS, same app version.

**Comment by inderdhir** [comment]
Can you try again with 5.0.0?

**Comment by highschooldropout** [comment]
> Can you try again with 5.0.0?

Seems to be working now with 5.1.0.
