### ISSUE TITLE
Unable to detect location using either lat/long or zip code

### ISSUE THREAD

**Issue by Jumbo-Bubbles** [inderdhir/DatWeatherDoe#134]
Unable to detect location using either lat/long or zip code

**Comment by inderdhir** [comment]
Can you provide more info? It seems to be working on my end. What lat/long and zip code are you trying?

**Comment by emcdade** [comment]
> Can you provide more info? It seems to be working on my end. What lat/long and zip code are you trying?

Hi - I am having this issue as well. No matter the selection (location, lat/long, zip) I get a location error message and this has been going on for a few months. I have tried with a series of zip codes (98105, 98229) and none work. I am using MacOS version 14.5 (23F79).

**Comment by inderdhir** [comment]
@emcdade @Jumbo-Bubbles  Can you try v5.0.0 and let me know?
