### ISSUE TITLE
Menu bar text sequence has flipped

### ISSUE THREAD

**Issue by pleaseinsertacoin** [inderdhir/DatWeatherDoe#136]
After a recent update (not sure if 4.1.2->4.1.3 or earlier), the menu bar item shows the temperature before the condition text, but retains capitalization on the condition (ie. "11°, Cloudy" – see screenshot below – instead of "Cloudy, 11º"). This looks weird and somewhat unnatural. Any chance we could get a tickbox or dropdown switch to decide where we want the condition text to go?

![image](https://github.com/inderdhir/DatWeatherDoe/assets/580750/baf84810-a9ad-47cf-b2af-8ac4d2c3d39b)

**Comment by inderdhir** [comment]
I believe this was done to keep the icon and the actual temperature together while keeping all the optional text in front of it.
<img width="175" alt="Screenshot 2024-02-29 at 10 45 34 AM" src="https://github.com/inderdhir/DatWeatherDoe/assets/2235307/2d97a33b-672f-419a-bf1b-d999c3d1adae">

**Comment by pleaseinsertacoin** [comment]
Ok, I see the logic behind that, but I think it would still be slightly better to give users a choice.

**Comment by inderdhir** [comment]
There is now an option to configure the placement of weather condition in 4.2.0. It should be available via homebrew cask shortly. Let me know if that works or feel free to reopen this issue.
