### ISSUE TITLE
api.openweathermap.org delivers 401 Unauthorized in response to API request

### ISSUE THREAD

**Issue by ednolan** [inderdhir/DatWeatherDoe#141]
DatWeatherDoe is showing a "The data couldn't be read because it is missing." error message. Investigating with Proxyman shows the following 401 Unauthorized error:

![Screenshot 2024-06-04 at 1 19 56 PM](https://github.com/inderdhir/DatWeatherDoe/assets/907967/4dacac1c-19ef-43c5-9578-e10be5fdb485)

This is for DatWeatherDoe version 4.2.2 installed via homebrew.

**Comment by inderdhir** [comment]
Fix incoming in the next release. I had an issue with API keys 😓

**Comment by inderdhir** [comment]
Release is up on Github, should be up on homebrew shortly.

**Comment by queenkjuul** [comment]
updated via homebrew and issue is resolved, thanks!!

**Comment by grr** [comment]
> Release is up on Github, should be up on homebrew shortly.

Will version 3.3 get this fix? Even though macOS 11 and 12 are no longer supported, you are still linking to it from the README.

**Comment by inderdhir** [comment]
@grr Good point since they are using the older API key, will fix.

**Comment by Sanseviearia** [comment]
Should we reactivate this issue since v3 has not been updated yet? In the meantime, is it possible to provide instructions on what changes need to be made in which file, so we can manually and temporarily "fix" v3?

Thanks!

**Comment by inderdhir** [comment]
I don't think we can update the prior versions since the old API key is baked in. There will be another piece of work this month to upgrade to OpenWeatherMap APi v3 as the current API is going to be shut down.

**Comment by Sanseviearia** [comment]
So, no go for v3 users. Any similar apps you can suggest for users who are stuck with old versions due to the older hardware they have?

Thanks!
