### ISSUE TITLE
Location input is greyed out in 5.0.0

### ISSUE THREAD

**Issue by Frederick888** [inderdhir/DatWeatherDoe#146]
<img width="371" alt="image" src="https://github.com/inderdhir/DatWeatherDoe/assets/4507647/02fd2a64-f260-4335-a7a3-48d59fd7298d">

I cannot fill in the location. The cursor keeps staying in 'Separate values with' input.

OS: macOS 14.5 (Intel)
Installed DatWeatherDoe from Homebrew.

**Comment by lsp199308** [comment]
If using location, please make sure that the app has permission to access location services on macOS.

System Preferences > Security & Privacy > Privacy > Location Services

**Comment by Frederick888** [comment]
I switched off location services. Is the 'city, country code' manual input gone in 5.0.0? If this is intentional, I can use Lat/Long instead :)

**Comment by lsp199308** [comment]
Only system location / latLong support to start with potentially more options in the future

**Comment by inderdhir** [comment]
I will experiment with some other options. City and zip code options have been troublesome in the past for folks outside the US so location / latlLong is probably ideal initially.
