### ISSUE TITLE
How to configure if installed with brew cask

### ISSUE THREAD

**Issue by lanmonster** [inderdhir/DatWeatherDoe#15]
I used `brew cask install datweatherdoe` and I see the app in my bar. how do I configure my api key? I don't see any plist files anywhere.

**Comment by BennetGom** [comment]
Right-Click DatWeatherDoe application in your applications folder. -> Show Package Contents -> Contents -> Resources

**Comment by inderdhir** [comment]
The API key is only required if you want to contribute to the project for testing. There's a default api key baked in to fetch weather so you should be good to go out of the box.
