### ISSUE TITLE
App Not Appearing on the Menu Bar in 5.2.0

### ISSUE THREAD

**Issue by seabassapologist** [inderdhir/DatWeatherDoe#156]
When trying to launch 5.2.0 on my machine, the app seems to start and is running in the background, but nothing appears on my menu bar. I can see the process from `ps` and while starting I can see in the command center that it's accessing location (which has been granted in Privacy & Security), but the menu bar app doesn't appear. If I install 5.1.0 it seems to launch normally. Tried uninstalling and reinstalling multiple times both from brew and straight from the .dmg file, and restarting the machine and nothing seems to work with 5.2.0

```
% ps -eaf | grep -i weather
  501  4228     1   0  4:56PM ??         0:00.11 /Applications/DatWeatherDoe.app/Contents/MacOS/DatWeatherDoe
  501  4230  1071   0  4:57PM ttys000    0:00.00 grep --color=auto -i weather
```

Macbook Air M2
Sonoma 14.5 (23F79)

**Comment by inderdhir** [comment]
Does the app show up when you use latitude / longtidude on 5.2.0?

**Comment by seabassapologist** [comment]
Hi, apologies for the delay. I did not try that on version 5.2.0, but I just now installed 5.2.1 and it's running correctly in the menu bar now
