### ISSUE TITLE
setting location

### ISSUE THREAD

**Issue by CouldBeThis** [inderdhir/DatWeatherDoe#16]
Hello, 

Trying to set up location for this manually. Got the API key in the plist file. Config box says  `zip code, iso 3166 country code`. 

Wikipedia has this document: [Current ISO 3166 country codes](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes#Current_ISO_3166_country_codes) and I am guessing the column "Alpha-2 code" is the right one because the example is `us`.

I live in Canada (`ca`), which has postal codes instead of zip codes. 

Here is an example: [Whitehorse](https://openweathermap.org/city/6180550) which contains the postal code for example `Y1A 0A1`

so tried `Y1A 0A1,ca`

Something annoying with postal codes is there will be some kind of validation on the format wrt capital letters and/or space. `A1A 1A1` is the most correct format.  I tried a couple different permutations but was unable to get this to work.`

Also tried `city name, country code` as that's how the website works.

by way of troubleshooting, `90210,us` does work.

Any thoughts?

**Comment by inderdhir** [comment]
I am getting a "city not found" for that zip code. It's possible that the given zip code is not in open weather map's predefined list.

I will go ahead and add a "lat,lon" option in the next release.

**Comment by CouldBeThis** [comment]
cool! never have to look out the window. :)

**Comment by inderdhir** [comment]
1.4.0 is out with lat/lon support. The priority is "location > zip code > lat/lon." Let me know if that works!
