### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Marc66** [inderdhir/DatWeatherDoe#17]
I would like to contribute and translate this nice application to French. Can you make the necessary (generic) fr.lproj available and I will gladly help

**Comment by Marc66** [comment]
Forget this request. I won't translate if I can't run this application on a MacOS version that is still supported by Apple

**Comment by inderdhir** [comment]
Hey @Marc66 , I have updated the repo with support for localization with the new way to do it). 
There are English strings under `Resources/Localization/en.xcloc`. Please check it out and let me know if you need anything. 

You will probably need a `fr.xcloc` in that same directory. Also there's a way to import localizations via `Product > Import Localizations`.

FYI: I was unable to see the contents of that `xcloc` file in Xcode 12.5 but it worked fine when I opened it using Xcode 13 Beta.

**Comment by inderdhir** [comment]
Seems like `xliff`files are contained within the new `xcloc` format. I have added the `en.xliff` here for reference:
https://gist.github.com/inderdhir/a90f259d0a1168685b0a3ed0c52ce52d

**Comment by Marc66** [comment]
I looked at en.xliff and it does not include the right text to translate. It includes text that we don't see in the app like open file, copy, paste, save, etc. but does not include any of the strings found in the [Configure] option like Unit, Source, refresh interval, show humidity, etc. I also don't see the text for various weather conditions (sunny, etc).

If I make a fr.xliff file from your en.xliff, we'll miss most of the stuff that should be translated

**Comment by inderdhir** [comment]
Hey @Marc66 , seems like I missed a few strings in code which resulted in Xcode not picking them up for `en.xliff`. I have updated the gist with the missing strings. All the strings for "Main Menu" like "open file", "copy" etc are being generated by Xcode manually as part of the menu bar so you can choose to ignore those. All of the strings under "Configure" should now be in the file: https://gist.github.com/inderdhir/a90f259d0a1168685b0a3ed0c52ce52d

**Comment by Marc66** [comment]
French Translation attached. Let me know if you can make it work
[datweatherdoe_fr.xliff.zip](https://github.com/inderdhir/DatWeatherDoe/files/6693090/datweatherdoe_fr.xliff.zip)

**Comment by inderdhir** [comment]
@Marc66 Everything is working. I also found 4 more strings that were not part of the original file. Let me know how these translations look:

```
/* Unknown weather location */
 "Unknown Location" = "Emplacement inconnu";

 /* Refresh weather */
 "Refresh" = "Rafraîchir";

 /* Configure app */
 "Configure" = "Configurer";

 /* Quit app */
 "Quit" = "Quitter";
```

**Comment by Marc66** [comment]
Translation of those 4 strings is good and one of them made me review 2 lines from my original xliff (I didn't have the context). Attached is my updated xliff
[datweatherdoe_fr.xliff.zip](https://github.com/inderdhir/DatWeatherDoe/files/6700602/datweatherdoe_fr.xliff.zip)

**Comment by inderdhir** [comment]
Thanks for the help! I will cut a new release today which will include French support ☕

**Comment by Marc66** [comment]
Looking good but for some reason, there's still a [Done] button in the configuration and I can't find this string in en.lproj or fr.lproj; it is probably hardcoded.

![French-Translation](https://user-images.githubusercontent.com/11850067/123422261-3daa3700-d5be-11eb-9bc8-56f3ca79cd3e.jpg)

**Comment by inderdhir** [comment]
I'll check

**Comment by inderdhir** [comment]
Found it! Is this the right translation?
```
/* Finish configuring app */
"Done" = "Fait";
```

**Comment by Marc66** [comment]
A better translation would be "Terminé" which means finished, completed

**Comment by inderdhir** [comment]
Fix release in 2.1.1, it will also be available via Homebrew cask shortly. Thanks again!

**Comment by Marc66** [comment]
Perfect. Thank you

**Comment by inderdhir** [comment]
Added a new string, let me know how this looks:

```
/* Location privacy error when app is not given permission to access location services */
"Location Privacy Error" = "Erreur de confidentialité de l'emplacement";
```
