### ISSUE TITLE
Does not launch in MacOS 11.1

### ISSUE THREAD

**Issue by VirtualDisk** [inderdhir/DatWeatherDoe#19]
Just updated MacOS as well as all of my brew formulae. Can post logs or additional info if needed.

**Comment by fxdpz** [comment]
same issue here. nothing happened after open the app. pls help.

**Comment by inderdhir** [comment]
Can you check if the app is running in Activity Monitor and if it has location permissions (if using location) in macOS Settings (Security & Privacy)?

PS: I am currently running it on macOS 11.1.

**Comment by fxdpz** [comment]
the app is running in Activity Monitor and location permissions has been granted. My OS is 11.1.
it's weired.

**Comment by inderdhir** [comment]
Can you uninstall and retry with [release 1.4.1](https://github.com/inderdhir/DatWeatherDoe/releases/download/1.4.1/DatWeatherDoe-1.4.1.dmg) (released today?). I am still waiting for my PR to be merged for Homebrew Cask.

**Comment by fxdpz** [comment]
same symptom using 1.4.1.

**Comment by inderdhir** [comment]
@VirtualDisk Any chance you can get me some logs please? Would be helpful to clone the project and try running it using Xcode if you can. You will also need an API key from openweathermap. (Check out "Developer Setup" on README)

**Comment by avk458** [comment]
I got this repeat error log from console 

> Invalid timestamps for HID response delay: 25659110878083 to 615818887043

**Comment by alienator88** [comment]
I'm also seeing this on macOS 10.15.7 on version 1.4.1. Also tried previous version.
It launches in Activity Monitor and permissions granted, but never shows up in menu bar.

**Comment by VirtualDisk** [comment]
Where can I find these logs? @inderdhir

**Comment by inderdhir** [comment]
There is a case when the API response fails and the app doesn't have an icon in the menu bar but it's still running. Can you confirm if this is indeed the case? If yes, we will know if it's an API issue.

@avk458 @alienator88 any chance you can get me the zip code that's causing the issue?
@VirtualDisk you would have to dig into the code to get logs in Xcode. 

<img width="187" alt="Screen Shot 2021-01-18 at 5 53 43 PM" src="https://user-images.githubusercontent.com/2235307/104969360-3c913000-59b6-11eb-80b8-f545d656a0b4.png">

**Comment by avk458** [comment]
@inderdhir Chongqing，China zip code should be 400000

**Comment by inderdhir** [comment]
OpenWeatheMap has issues with non-American zipcodes (See #16). Can you please retry with "Use location" or "Lat/long"?

**Comment by alienator88** [comment]
> There is a case when the API response fails and the app doesn't have an icon in the menu bar but it's still running. Can you confirm if this is indeed the case? If yes, we will know if it's an API issue.
> 
> @avk458 @alienator88 any chance you can get me the zip code that's causing the issue?
> @VirtualDisk you would have to dig into the code to get logs in Xcode.
> 
> <img alt="Screen Shot 2021-01-18 at 5 53 43 PM" width="187" src="https://user-images.githubusercontent.com/2235307/104969360-3c913000-59b6-11eb-80b8-f545d656a0b4.png">

Hi there,
I was never able to configure a zip code since the app was never launched successfully after install.
If the app is pulling the zip code automatically, it's looking for 84096.

**Comment by inderdhir** [comment]
@alienator88 I just verified that zip code `84096` is working.

<img width="493" alt="Screen Shot 2021-01-23 at 8 30 29 PM" src="https://user-images.githubusercontent.com/2235307/105618840-ea874a80-5db9-11eb-89d9-b5e698bf9c36.png">

**Comment by inderdhir** [comment]
@avk458 @alienator88 
- Zip code 400000 seems to work
- Lat long value (30.108589,107.747222) for Chongqing without any spaces also works.

**Comment by alienator88** [comment]
@inderdhir In my case I was never able to get the application to launch and configure the zip code. I see that the zip code works in your case, but it doesn't seem to open in the menu bar. I checked for the blank/no icon issue as well. I do see it in Activity Monitor though.

**Comment by inderdhir** [comment]
@alienator88 2.0.0 is out! Can you please retry with that version?

**Comment by xmacinfo** [comment]
I tries 2.1.1 on macOS 11.4 and DatWeatherDoe does not launch.

**Comment by xmacinfo** [comment]
Solved, DatWeatherDoe does not ask for permission to use the location services.

After manually giving it permission through System Preferences to use location services, it started to display in the menu bar.

Additional checks in the application should warn the user and display the menu bar item even in location service is not enabled. So that the app can ask the user in a nice message to give it the proper permission.

**Comment by xmacinfo** [comment]
Awesome, 2.1.2 will fix the location issue:  

https://github.com/inderdhir/DatWeatherDoe/pull/43
