### ISSUE TITLE
Feature Request: Display °C and °F

### ISSUE THREAD

**Issue by bdarfler** [inderdhir/DatWeatherDoe#28]
I would love a way to display both so that I can communicate the weather to my co-workers who live in different countries.

**Comment by brent-riva** [comment]
Marking this in case I have time later, but it looks like it can be added here: 

https://github.com/inderdhir/DatWeatherDoe/blob/master/DatWeatherDoe/WeatherResponse.swift#L86-L93

**Comment by bdarfler** [comment]
@brent-riva Oh no, I don't think I was clear enough. I'd like to have the widget display the temp in both Celsius and Fahrenheit so that I can talk to people in different countries about the temperature at my location.

That said, I do like the idea of at least displaying the °C or °F. I guess that would be a necessary first step anyhow.

**Comment by inderdhir** [comment]
@bdarfler 2.0.0 is out which includes support for showing weather in both C and F simultaneously!

**Comment by bdarfler** [comment]
SWEET! Thanks @inderdhir !
