### ISSUE TITLE
Feature request: Add link in menu to see full forecast

### ISSUE THREAD

**Issue by daviddavis** [inderdhir/DatWeatherDoe#51]
I'd love to see a full weather forecast in the menu (see #38) but I figure it might be easier for now to add a menu item that when clicked opens `https://openweathermap.org/city/...` in the browser.

**Comment by inderdhir** [comment]
Added in next release https://github.com/inderdhir/DatWeatherDoe/pull/53/ , will update here when it's live ☕

**Comment by inderdhir** [comment]
Out now in 2.1.5

**Comment by daviddavis** [comment]
This works great. 👍 

Thanks!

**Comment by grr** [comment]
Doesn't work if the weather source is set to zip code. The city id defaults to 0, which links to London. Surprisingly, using Lat/Long does work as expected.

**Comment by inderdhir** [comment]
@grr Interesting, seems like an issue with the API. It always returns `0` for city ID when the weather is fetched using zip code 😢
