### ISSUE TITLE
Icon disappears

### ISSUE THREAD

**Issue by grr** [inderdhir/DatWeatherDoe#56]
Sometimes the icon disappears and it only shows the temperature. Refreshing or re-configuring with a different location, etc. never get it to display again. Occasionally restarting will get it to show again, but not always. Changed desktop appearance from dark to light to make sure it wasn't a case of black image on black background, but not the case. So it might be a data issue from the api, though pulling up the page on openweathermap.org looks normal. Maybe there should also be a link to the api output, to better help debug.

**Comment by inderdhir** [comment]
I saw this once recently, might be a new / unknown weather code that's coming back from the API. I will check.

**Comment by inderdhir** [comment]
Fixed in 2.1.6
