### ISSUE TITLE
If Location is set manually (using Zip code) then "See Full Weather" doesn't work

### ISSUE THREAD

**Issue by luckman212** [inderdhir/DatWeatherDoe#58]
I noticed that if I configure DatWeatherDoe with my zipcode e.g. `10021,us` then it successfully retreives the conditions for the menubar, but choosing **See Full Weather** results in a browser URL of https://openweathermap.org/city/0 which is invalid.

I don't really see anything in the openweather API to map zip codes to city IDs or names, so maybe in lieu of that, adding a config field for manually inputting `cityId` and then using that [here](https://github.com/inderdhir/DatWeatherDoe/blob/49ef37fcdf8f028b5fae7a19fa927738c3365616/DatWeatherDoe/AppDelegate.swift#L114) would be a workaround?

**Comment by inderdhir** [comment]
It appears that the OpenWeatherMap API returns a city code of 0 every time we get current weather data using zip code. I have filed a support ticket with them. I will post an update here if and when I hear back from them.

**Comment by inderdhir** [comment]
Closing this for now as this is a limitation of the OpenWeatherMap API and I haven't heard from them.
