### ISSUE TITLE
Incorrect categorisation of weather

### ISSUE THREAD

**Issue by JonoHaysom** [inderdhir/DatWeatherDoe#59]
Love the app, thanks for the hard work!

just noticed "dust" as reported by TheWeatherMap is showing up as "mist" by the app. cant his be fixed please?

screen shot showing the menubar and the actual weather as reported by TWM

<img width="162" alt="Screen Shot 2022-01-02 at 3 10 14 pm" src="https://user-images.githubusercontent.com/8393299/147874416-1456b918-3ad2-4fda-ac5e-841af7afe44d.png">
<img width="985" alt="Screen Shot 2022-01-02 at 3 10 17 pm" src="https://user-images.githubusercontent.com/8393299/147874417-30ca9934-f0d5-4a34-9320-922520394b4b.png">

**Comment by inderdhir** [comment]
Fix coming in https://github.com/inderdhir/DatWeatherDoe/pull/60

**Comment by inderdhir** [comment]
The fix is included in 2.2.0 which was just released!
