### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by teedoff087** [inderdhir/DatWeatherDoe#68]
On macOS 11.6.2 (Big Sur), using DWD 3.0.1, the menu bar icon just says "Network Error." I tried trashing the app and removing all preferences. Disabling firewall temporarily doesn't solve the issue. Even manually entering the ZIP code with country code (e.g. 7****,us) doesn't work. DWD 2.2.0 works perfectly.

**Comment by inderdhir** [comment]
It seems like the API key may have been missing from that release. Sorry about that. Fixed in 3.0.2
