### ISSUE TITLE
Show more info in the dropdown

### ISSUE THREAD

**Issue by daviddavis** [inderdhir/DatWeatherDoe#74]
It'd be great to see more information in the drop down such as:

* Feels like temperature
* Weather text (eg "Overcast clouds")
* Wind speed
* Humidity

**Comment by daviddavis** [comment]
Maybe a 3-day forecast too?

**Comment by inderdhir** [comment]
Hey @daviddavis , 8 day forecast is visible upon clicking "See Full Weather." I'll take a look at the other info.

**Comment by grr** [comment]
Extra info could be displayed similarly to how new free, but not open source, app Qwik does it:
https://widgetworx.com/apps/qwik_weather.html

**Comment by inderdhir** [comment]
Added extra data in 3.0.3, should be available via Hombrew Cask shortly
