### ISSUE TITLE
Zip Code Error

### ISSUE THREAD

**Issue by highschooldropout** [inderdhir/DatWeatherDoe#75]
Location is off on the Mac being used. In order to get data, zip code or latitude/longitude must be used. While the latter works fine. the former option, zip code, returns an error: Zip Code Error. I have tried uninstalling and reinstalling via Homebrew but the issue persists.

**Comment by inderdhir** [comment]
Can you tell me what zip code you are using?

**Comment by highschooldropout** [comment]
Most recently 11237. Several zip codes have been inputted but the error persists.

**Comment by seathasky** [comment]
> Try using your zip code, and the country code. So for the US, it would be 11237,US
This worked for me, thanks!
